{% set name = "libuvc" %}
{% set version = "0.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 7c6ba79723ad5d0ccdfbe6cadcfbd03f9f75b701d7ba96631eb1fd929a86ee72

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libusb
    - libjpeg-turbo

test:
  commands:
    - test -f ${PREFIX}/include/libuvc/libuvc.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\libuvc\libuvc.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/libuvc/libuvc/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: libuvc is a cross-platform library for USB video devices, built atop libusb

extra:
  recipe-maintainers:
    - Tobias-Fischer
